CREATE DATABASE WISHLIST_G4
USE WISHLIST_G4

CREATE TABLE USUARIOS (
    idUsuario TINYINT PRIMARY KEY IDENTITY,
    nome VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL,
    senha VARCHAR(30) NOT NULL
);
GO

CREATE TABLE DESEJOS (
    idDesejo TINYINT PRIMARY KEY IDENTITY,
    idUsuario TINYINT FOREIGN KEY REFERENCES USUARIOS(idUsuario)
    descricao VARCHAR(100)
);
GO
